# switch this to true you want to start in DEVMODE
# https://www.vaultproject.io/intro/getting-started/dev-server.html
[dev]
mode = false

[backend]
use-https = false
storage = "file"
path = "vault/"
service-name = "vault"

[listener]
type = "tcp"
location = "127.0.0.1"
port = "8200"
tls_disable = "1"

[server]
ui = true
