#!/bin/bash -xe

exec 2>&1

DEVMODE={{cfg.dev.mode}}

if [ "$DEVMODE" = true ] ; then
  exec {{pkgPathFor "core/vault"}}/bin/vault server -dev-listen-address=0.0.0.0:8200 -dev
else
  exec {{pkgPathFor "core/vault"}}/bin/vault server -config={{pkg.svc_config_path}}/settings.hcl
fi
